### ISSUE TITLE
Editor crashes on startup

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#111]
Reinstalled PGE via online installer and on editor startup got this:
![crash1](https://cloud.githubusercontent.com/assets/7596025/14231443/240f636a-f98c-11e5-8556-9b851d2f0b4e.png)

**Comment by Wohlstand** [comment]
Try to take build from laboratory, (also apply the config pack patch from the bottom!)

**Comment by Alucard648** [comment]
Thanks.

**Comment by Alucard648** [comment]
On the other hand, online installer is not updated to latest PGE version.
