### ISSUE TITLE
Closing inactive level's tab kills active level's music (See video)

### ISSUE THREAD

**Issue by jpmac26** [Wohlhabend-Networks/PGE-Project#114]
See this video for more info on the bug: [https://www.youtube.com/watch?v=7r9M6HAiVaA&feature=youtu.be](url)

**Comment by Wohlstand** [comment]
Ouch, I missed something in the events, I need to check out that stuff again...

**Comment by Alucard648** [comment]
Also editor`s music player does not resume playback when engine ran for level test terminates. Need to press F11 after every test run.

**Comment by Wohlstand** [comment]
Alucard648, that old imperfection, and to finish that part I need to remember last state of music button and when engine process finished - restore music back

**Comment by Wohlstand** [comment]
Everything will appear in the laboratory (configuration package is not needed for update)

**Comment by Wohlstand** [comment]
Everything has been fixed
