### ISSUE TITLE
[Engine] Issues with slopes

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#115]
1. When character goes down slope at full speed and encounters a solid block, he can phase trough it
![scr_2016_4_17_23_15_13_364](https://cloud.githubusercontent.com/assets/7596025/14589775/d83a26ec-04f2-11e6-89ae-b83dfc5d4746.png)
2. When character walks on top or slope block, his animation jitters, and he is unable to jump in this state.
![scr_2016_4_17_23_15_31_708](https://cloud.githubusercontent.com/assets/7596025/14589787/495b027e-04f3-11e6-87f1-bba41855efdf.png)
Test level: https://yadi.sk/d/96iEi09Kr5E8B

**Comment by Wohlstand** [comment]
That my old imperfection of physics where slope detection on edges still be missing: To finally resolve this I need check more conditions around in the collision formula.

P.S. Until I zoomed out and paused animation in the editor, was too hard read a ```БУЛТЫХ!``` word made with coins in the bonus room, was a funny :laughing:

**Comment by Wohlstand** [comment]
With upgrated physics this no more happens
