### ISSUE TITLE
[Engine] Issues with moving layers

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#116]
Did some extensive testing of moving layes and apart from unimplemented crushing...
- [x] 1. Character sometimes can get stuck and unable to walk and jump on upwards moving layer
https://yadi.sk/d/igPETEleqjKxh
- [x] 2. If horizontally moving layer tries to push character while he is facing away from it, he will phase trough moving layer.
- [x] 3. It`s impossible to jump properly when pushed by horizontally moving layer.
Test level for horizontally moving layers: https://yadi.sk/d/BvCfs70Mr5ERT

**Comment by Wohlstand** [comment]
Moving layer engine wasn't finished yet, also it's currently is not so optimal and too much elements would lag game loop. Optimal solution is dedicating separated R-Trees per every moving layer and let elements take offset value dependent to layer motion subsystem. Speed-adding stack implementation is not so perfect too, it needs more stability.
P.S> You forgot to put musics for a first test level

**Comment by Wohlstand** [comment]
All bugs here no more happens

**Comment by Wohlstand** [comment]
P.S. that MIDI will playing better if you will use 62'th bank:
```
furnace1a.mid|b62;t0;v0;
```
t0 and v0 are optional. Just because in original game those flags was been disabled
