### ISSUE TITLE
[Editor] Update checker utility fails to detect newest releases and laboratory builds.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#118]
Title says all.
![updatebug1](https://cloud.githubusercontent.com/assets/7596025/14712675/c3ac8886-07e6-11e6-94d6-348781b8f88d.png)
![updatebug2](https://cloud.githubusercontent.com/assets/7596025/14712679/c6d49ac6-07e6-11e6-9b0f-5d2577d150d3.png)

**Comment by Wohlstand** [comment]
That because my server-side scripts are wrong and there are wasn't updated targeted TXT-files which are contains actual version number, also I'll improve version comparison to check updates by a build dates base instead of version number to easier compare build time

**Comment by Wohlstand** [comment]
Anyway, laboratory build checker was invalid all time, and it must reply "latest version" always when build date greater than remote date, also I will provide different dates per different platforms: Linux, Windows, OS X, because CI's are builds same project with a different time

**Comment by Wohlstand** [comment]
I fixed it long time ago, and now it correctly showing data of the update
