### ISSUE TITLE
[Online installer NSIS] Avast treats newest online installer as virus.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#121]
Title says all.
![virus 1](https://cloud.githubusercontent.com/assets/7596025/14935311/1ce12368-0ed5-11e6-8654-6c006eab8f52.png)

**Comment by Wohlstand** [comment]
Avast is famous because false-alert-full, but try to build installer yourself: all required files are at:
_Misc/dev-scripts/deploy/nsis
To build installer need to take NSIS and some plugins for it (links inside readme.txt)

**Comment by Wohlstand** [comment]
``` Hello,


Thank you for contacting AVAST Software s.r.o. with your concerns.


The provided file isn't detected by Avast with the latest Virus Definitions. Please update your Virus Definitions by following these steps: Open Avast program and go to > Settings > Update > VIRUS DEFINITIONS > Update.

If the problem persists, please send me a screenshot of the detection message. On this website you can learn how to take a screenshot: http://take-a-screenshot.org/


Best regards,

Prokop Kalivoda

Avast Technical Support Specialist```

**Comment by Alucard648** [comment]
The editor still crashes on startup, if PGE was installed from online installer downloaded from site.

**Comment by Wohlstand** [comment]
Try same install with toggled off antivirus, that VERY wired

**Comment by Alucard648** [comment]
Did uninstall then fresh install with antivirus off. Same result. Portable version works fine.

Also. Ran CCleaner after uninstallation and it found some registry junk left from PGE:
![uninstall_junk](https://cloud.githubusercontent.com/assets/7596025/14959548/8584d6f2-1098-11e6-8a3b-3ba99a7a1571.png)

**Comment by Wohlstand** [comment]
1) Your Windows version? (Non-portable installation asks registry entries for some, portable version never checks system registry. I'll try some on Windows 10 at VirtualBox).
2) Wait a sec, I'll add removing of file association registry keys on uninstall

**Comment by Alucard648** [comment]
1. Windows 7 SP1.

**Comment by Wohlstand** [comment]
Try this installer:
http://wohlsoft.ru/PGE/_downloads/win32/pge-online-downloader.exe
(Just updated)

**Comment by Alucard648** [comment]
Avast blocks dowload. Again.

**Comment by Wohlstand** [comment]
1) Try to update your antivirus bases
2) Try to report false alert yourself or tell me your antivirus version, base, spec. to allow me tell them that false alert still presented
3) Download with disabled avast

**Comment by Alucard648** [comment]
Installation went fine. Editor still crashes...

**Comment by Wohlstand** [comment]
1) Show me your installation folder contents
2) Unpack portable build into separated folder
3) move out all config packs into separated place (temporary)
4) Use this tool http://meldmerge.org/ to compare both folders and show me result
differences are must be:
- logs/screenshots/world/calibrator folders in portable
- pge_editor.ini/pge_engine.ini/pge_calibrator.ini in portable
- uninstall.exe in the installed
If some DLLs in installed are missed or different (also inside "platform" folder), that a reason

**Comment by Wohlstand** [comment]
EDIT: Oh, dammit!! Both portable and instalable packages for Windows are has missed DLLs in "platforms" and "imageformats" which are must be presented (there are required!)

**Comment by Wohlstand** [comment]
Okay, true reason why online-installed editor crashing - access denied to write files and folder creation into same folder (program files) which protected from writing. Online installer accidentally generated INI-files which are tells to editor, engine and calibrator work in portable mode that requires write access to same folder. I fixed that and fixed installer I'll upload now.

**Comment by Wohlstand** [comment]
Also, DRep is a paranoic treat "File is not famous", so, don't worry

**Comment by Wohlstand** [comment]
```TEXT
Hi,


Thank you for your response.


Our virus specialists have been working on this problem and it has now been resolved. The provided file isn't detected by Avast anymore.


Please check the following articles about Avast virus policy:

Avast Clean Guidelines: https://www.avast.com/faq.php?article=AVKB228Avast File Whitelisting: https://www.avast.com/en-us/faq.php?article=AVKB229


We are sorry for the inconvenience. If you have any further questions, don't hesitate to contact me again.


Best regards,

Prokop Kalivoda

Avast Technical Support Specialist

On Thu, 5 May at 9:50 AM , Admin <admin@wohlnet.ru> wrote:

Hello!

I forgot to say that was a DRep alert.


My opinion at this:

I hate this technology, because it scaring people with false alerts. Good to know that smart people are reporting me about those alerts. I think you must warning softer, but don't lock hard because "file is not famous". Signing executables with a signatures is not cheap thing. Even my applications are not requires admin rights. Installer requires once.


Отправлено с Samsung Mobile



-------- Исходное сообщение --------
От: Avast Customer Care 
Дата:05.05.2016 10:17 (GMT+03:00) 
Кому: admin@wohlnet.ru 
Тема: We are closing your support request ( Ticket ID: [#304342] ) 

Dear Admin,

This is just a friendly reminder about your support request.


We have not heard from you in several days regarding the ticket below.


Ticket ID: 304342
Subject: Suspected false positive file - pge-online-downloader.exe

If you do not need any more help, we will consider this ticket closed.


If you still need help with this issue, please reply online at:

https://support.avast.com/helpdesk/tickets/304342


The ticket will be re-opened by your response so that we can continue to assist you.If you have any further questions, please let us know.
 

Kind regards,


The Support Team

AVAST Software


304342
```

**Comment by Wohlstand** [comment]
Are you still have treat or it has been fixed?

**Comment by Alucard648** [comment]
Awast still blocks download.

**Comment by Wohlstand** [comment]
Anyway, please add exception, because "DRep" is "File is not famouse" which a paranoia, and keep base up to date

**Comment by Alucard648** [comment]
As for now, it can also blocks download as Wn32.EvoGen[Susp].
![virus2](https://cloud.githubusercontent.com/assets/7596025/15159942/db83c24e-16ff-11e6-9d7b-e6a5a4755d33.png)

**Comment by Wohlstand** [comment]
Still false alert:
https://forum.avast.com/index.php?topic=140712.0

**Comment by Wohlstand** [comment]
Try this (Version of installer which requires no admin rights and installs into AppData folder in user profile instead of program files):
http://wohlsoft.ru/PGE/_downloads/win32/pge-online-downloader-noadmin.exe
And a dummy installer which just says "hello world" and doing nothing:
http://wohlsoft.ru/PGE/_downloads/win32/hello_nsis.exe

**Comment by Alucard648** [comment]
Avast has blocked both provided downloads. I am hoping it won`t rule out Avast users...

**Comment by Wohlstand** [comment]
Thing is - second is a DUMMY installer which doing nothing, just spawns message box
```NSIS
# set the name of the installer
Outfile "hello world.exe"
 
# create a default section.
Section
 
# create a popup box, with an OK button and the text "Hello world!"
MessageBox MB_OK "Hello world!"
 
SectionEnd
```

**Comment by Alucard648** [comment]
As I said before "hello_nsis" was blocked as Drep. :-(

**Comment by Wohlstand** [comment]
Okay, I just sent to them another letter, waiting their reply

**Comment by Wohlstand** [comment]
Just a small trivia: http://nsis.sourceforge.net/mediawiki/index.php?title=NSIS_False_Positives&oldid=16520

**Comment by Wohlstand** [comment]
Does installer still be treated? (I wasnt changed it long time)

**Comment by Alucard648** [comment]
Latest laboratory build works fine.

**Comment by Wohlstand** [comment]
Okay, how Avast team told, when multiple users will mark this DRep as "safe", it will be no more detected
