### ISSUE TITLE
[Editor] "Clone section" command cannot be applied to sections > 21

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#122]
Whenever I try to clone section to another initialized one, even if it has nothing inside it, I got this:
![clone_issue](https://cloud.githubusercontent.com/assets/7596025/15139393/8a018412-169e-11e6-9769-878295601ec8.png)
I don`t even get prompt to overwrite target section. And if I delete that section via "Delete section" command, it is gone for good, assuming, it is > 21, which means it will not be visible in "Clone section" dialog box.

**Comment by Wohlstand** [comment]
So, I think, I need to add "init XXX section" as cloning target to allow section cloning into sections more than 21

**Comment by Wohlstand** [comment]
Made, so, in the tail of target sections list will be "Initialize section ..." field which allows you to clone section into new zone

**Comment by Alucard648** [comment]
I would also suggest so "Clone Section" dialog box would not auto-close when performing cloning so one would not have to reopen dialog again and again, when mass-cloning sections. No one wants having to assign background and music from huge list to 50+ sections Massive dungeon level can have many more than 50 sections...

**Comment by Wohlstand** [comment]
I just replaced notify about successful section cloning a question to clone again
