### ISSUE TITLE
Typo in Level menu command.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#124]
Scraanshot says all:
![typoe](https://cloud.githubusercontent.com/assets/7596025/16350941/9cfe277e-3a6a-11e6-85cc-932af4e6dc0e.png)
Wrap Vertically

**Comment by Wohlstand** [comment]
It's fine in the form, but typo was in TS-file, just fixed :wink:

**Comment by Alucard648** [comment]
"Horizontally"
