### ISSUE TITLE
Editor crashes when trying to define any event action in "Change Section Settings" group for sections>21.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#125]
Title says all.
![pgecrash2](https://cloud.githubusercontent.com/assets/7596025/16359139/06c7e8a8-3b32-11e6-9137-f1864b20ba33.png)
Test level: https://yadi.sk/d/BvCfs70Mr5ERT
Event "PotolokStart" should change music in section 29 to custom slot.
Also pair of typos in crash message: 
1. "Editor was crashed". Should be "Editor has crashed".
2. "Detail". Should be "Detailed" here.

**Comment by Wohlstand** [comment]
Oh, I see I has been missed up a thing when I adding support of >21 sections, that is not hard to fix
