### ISSUE TITLE
[Editor] Too many newlines between log entries

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#126]
http://pastebin.com/06fTNM3j
As we can see, log entries are separated by 9 empty rows. This issue affects in-editor development console.

**Comment by Wohlstand** [comment]
Strongly :yum: 
I need to check that

**Comment by Wohlstand** [comment]
I just checked, in editor printing is fine (tested on Linux). But I did some, please try that
