### ISSUE TITLE
Online downloader installs outdated build.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#133]
Checked online installer from laboratory, and it downloads and installs build as old as May 2016.

**Comment by Wohlstand** [comment]
Online installer download RELEASE build (which is very old now), not laboratory. Especially for laboratory, I think, I'll make separated installer wich will have specific icon/background to don't confuse release and dev.

**Comment by Wohlstand** [comment]
Okay, I just made the installer epspecially for laboratory builds, and it will don't confuse anymore with "stable" builds:
http://wohlsoft.ru/docs/_laboratory/_Builds/win32/pge-dev-online-downloader.exe
![newlabonlineinstaller](https://cloud.githubusercontent.com/assets/6751442/18084063/e28612d6-6eb6-11e6-8dd8-0969bafeaa48.png)

**Comment by Alucard648** [comment]
I can`t download that installer. Avast insta-blocks download (DRep) without an option to ignore it.

**Comment by Wohlstand** [comment]
So, just power off it while you downloading it. It's paranoid shit, not an antivirus which blocks files "which are not known" (file I generated in moment of creating that post)

**Comment by Alucard648** [comment]
> But please send me version of antivirus and it's base

![avast_about](https://cloud.githubusercontent.com/assets/7596025/18087121/25c9ffa8-6ebc-11e6-924a-799ce36d3106.png)
![avast_about1](https://cloud.githubusercontent.com/assets/7596025/18087154/5a4a0c96-6ebc-11e6-8a26-982093ee919f.png)

**Comment by Wohlstand** [comment]
Again same banal reply :yum: 
```
Добрый день,
Спасибо за Ваше письмо.
Тип угрозы Drep означает низкую (не проверенную) репутацию источника, откуда этот файл скачивается. Кроме того, это означает, что файл еще новый и не был как следует проанализирован. 
Если Вы являетесь разработчиком данной программы - то можете добавить цифровую подпись к файлу и предупреждение исчезнет сразу. 
Либо просто подождите пока определенное число пользователей Avast не попытается этот файл скачать. 
```
So, just ignore this alert and force your antivirus don't treat those files. Any non-DRep alerts must be reported

**Comment by Wohlstand** [comment]
But next letter there are suggested me download file from ten different devices to unblock a file. So, I'll just try to make a ten VirtualBox machines with Avast especially to do that :-P

**Comment by Alucard648** [comment]
Thanks, now working.

**Comment by Wohlstand** [comment]
Heh, I did nothing, but since it self-fixed, no needed. But Ill setup that to prevent same issues with other files.
As developer I hate Avast's paranoia :stuck_out_tongue_winking_eye: 
so, I closing this issue
