### ISSUE TITLE
Editor fails to open level with "quote" symbols in messages.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#136]
Title says all.
![badfile](https://cloud.githubusercontent.com/assets/7596025/18102270/a6e0bfee-6efa-11e6-880b-bcf7f256506a.png)

**Comment by Wohlstand** [comment]
String is really invalid (not going be valid CSV-stgring which making those files be invalid even for some cases of SMBX itself (and there are even can crash SMBX!). So, PGE File Library is automatically removes any quote signs from string fields until to generate file.). If that file made by other person, I'll try to make auto-correcting for this to don't flag file be invalid.
