### ISSUE TITLE
Minor mishap with editor settings window.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#137]
![editor_settings1](https://cloud.githubusercontent.com/assets/7596025/18230428/cc395c7c-72a3-11e6-9e39-c05a2c00caed.png)
Frames apparently overlap.

**Comment by Wohlstand** [comment]
That seems done accidentally while I fixed worse glitches on OS X. Even I added macro to apply this on OS X only, but I'll check and fix that

**Comment by Alucard648** [comment]
Fix confirmed.
