### ISSUE TITLE
Issues with horizontal pipe warps

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#138]
Character is unable to enter horizontal pipe warps right after landing right in front of them.
https://yadi.sk/i/1q37NetRukhq7

**Comment by Wohlstand** [comment]
This fixed just now!
Will appear in next commit, but now I can't push until I'll finish some works (fixing accuracy of time iterations, because some timers are mismatching in comparison to SMBX Engine)
