### ISSUE TITLE
Issues with SMBX integration config pack

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#140]
- [x] 1. Hitting F5 while Luna-LUA SMBX engine is not launched just launches SMBX launcher with nothing passed. Running SMBX legacy editor just opens empty file, like File->New. And upon closing legacy editor I got this:

![luna-lua2](https://cloud.githubusercontent.com/assets/7596025/18276271/f4fe7b5a-7452-11e6-87e0-c5759a4a4080.png)

- [x] 2. If I launch SMBX legacy editor beforehand (like following old method of testing levels in LunaLUA-SMBX) then hitting F5, which means running LUA Tester works fine. But if the level had some unsaved changes, I got this broken save confirmation dialog, effectively hanging PGE editor dead on.
![luna-lua](https://cloud.githubusercontent.com/assets/7596025/18276485/d49d2e0a-7453-11e6-967c-9e83ec02fe46.png)

PGE 0.4.0 Luna-LUA 0.7.3

**Comment by Wohlstand** [comment]
1) LunaLUA must be latest night dev, minimum requirement 0.7.3.1 (which buildable by AppVeyor)
2) OH MY, it's VERY wired, and that because some threading troubles-set. Wait a sec, i'll check out that

**Comment by Wohlstand** [comment]
First must work with super-latest (find the "or download night/dev build" url under list of  versions), and then issue can be closed

**Comment by Alucard648** [comment]
Ok. Thanks.

**Comment by Wohlstand** [comment]
I'll mark first item as "solved", because this must be with legacy LunaLUA builds, and that feature supported only since LunaLUA 0.7.3.1
