### ISSUE TITLE
Issues with slope aligning

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#143]
Character with "Align on slope-top" on fails to align with slope going down.
![slope1](https://cloud.githubusercontent.com/assets/7596025/18354465/5a938798-75ee-11e6-99af-1474e5e5d5fd.png)
Test level: https://yadi.sk/d/UFgy_2jjuuTJr
I didn`t know it was intantional or not until running Luna-Lua. In Luna-Lua-SMBX, slope aligning was fine...

**Comment by Wohlstand** [comment]
The alignment works when you rising sloe up, but yea, this part I wasn't implemented yet

**Comment by Wohlstand** [comment]
That just now been fixed (try laboratory build)

**Comment by Alucard648** [comment]
It works! Thanks.
