### ISSUE TITLE
PGE Engine executable fails to display it`s icon in Windows Explorer

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#144]
Title says all.
![iconbug](https://cloud.githubusercontent.com/assets/7596025/18354660/0f93804e-75ef-11e6-9039-1271e972b185.png)

**Comment by Wohlstand** [comment]
That a Windows-specific bug, and cache rebuilding is required (can be done via Microanglero 5 in "On Display" tab)

**Comment by Alucard648** [comment]
Icon cache rebuilding has fixed the bug.
