### ISSUE TITLE
Death in autoscrolling level results in screen blackening 

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#145]
Title says all.
![scr_2016_9_6_20_53_26_119](https://cloud.githubusercontent.com/assets/7596025/18357311/317d0e8c-75f9-11e6-8a9f-030412d200c1.png)
Test level: https://yadi.sk/d/hygZESD9uubYx

**Comment by Wohlstand** [comment]
Fixed! please check

**Comment by Alucard648** [comment]
Works fine, camera continues autoscrolling after death.
