### ISSUE TITLE
NPC generator properties editor. Direction selector partially overlapped by layer slots.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#44]
![npc_gen_editor_bug](https://cloud.githubusercontent.com/assets/7596025/7447165/57ac4698-f1f9-11e4-8907-d96675a4d0ce.png)
This issue exists only for NPC`s with special options, like firebar segments.
Windows 7.  0.3.0

**Comment by Wohlstand** [comment]
Oops :stuck_out_tongue_winking_eye:
I need to append minimal height for generator container
Anyway you can try to expand height of properties box and this thing will disappear.
![-8](https://cloud.githubusercontent.com/assets/6751442/7447546/a34edf5e-f1f7-11e4-9f28-53cb4d8a25a9.png)
![-9](https://cloud.githubusercontent.com/assets/6751442/7447549/a6ad11d4-f1f7-11e4-9928-87098825a2ae.png)

**Comment by Wohlstand** [comment]
I has been fixed it, get build from laboratory ;-)
P.S. Config packs too, therefore I have small bugfixes in npc-200 where fix wrong height and changes in the engine.ini and lvl_characters.ini which was updated.
