### ISSUE TITLE
Add selectable options for Message Box. 

### ISSUE THREAD

**Issue by KevinW1998** [Wohlhabend-Networks/PGE-Project#46]
I would like to see some sort of a "small menu" for messagebox. Like the default messagebox from windows has options "Yes", "No", "Cancel", ect...

**Comment by Wohlstand** [comment]
It will be a question box. I will manage for it together with a text-input box which allows to get typed text

**Comment by bstory2001** [comment]
I'm new around here and haven't had a chance to read any design goals.  Is Gamepad support any type of priority?  I really feel platform gaming is best with a gamepad and typing with a gamepad would require something like an on-screen keyboard.

**Comment by KevinW1998** [comment]
Uhm, that's already implemented.

**Comment by bstory2001** [comment]
Oh I see, I didn't see any on screen keyboard in the editor sorry.

**Comment by Wohlstand** [comment]
Menubox and question box are been implemented
