### ISSUE TITLE
MIDI`s don`t play at all

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#54]
This issue is apparent in editor 0.3.1, not in earlier versions.
When using MIDI as custom music, it does not play at all in editor. All other formats, like MP3, or SPC, work fine.

**Comment by Wohlstand** [comment]
The reason is your MIDI driver [Microsoft GS sucks!]. I think you need to:
* install this custom MIDI driver http://engine.wohlnet.ru/docs/Sounds/SMBX_OPL/opl3synth.zip
* then install bassmidi https://kode54.net/bassmididrv/bassmididrv.exe and use it's switcher to set "Yamaha OPL Synth" as MIDI device

**Comment by Alucard648** [comment]
But why MIDI`s play correctly in 0.3.0? 0.3.0 has managed to play Circus Galop (test MIDI) all the way to the end without any kinks.
Anyway, I am hoping, this new MIDI driver supports switching to different MIDI soundbanks. I already got used to GeneralMIDI soundbank for 12 years of PC usage.

**Comment by Wohlstand** [comment]
You can use "Yamaha OPL Synth" emulated chip synthesiser of 1980-90x years or you can use BassMIDI wavesynth with custom SF2 banks

**Comment by Alucard648** [comment]
I also would want to see a soundfont that emulates Microsoft`s General MIDI music.
https://kode54.net/bassmididrv/bassmididrv.exe - 404 not found.

**Comment by Wohlstand** [comment]
Okay, than get it via my mirror: http://engine.wohlnet.ru/docs/Software/bassmididrv.exe

**Comment by Alucard648** [comment]
Got a error while installing BassMIDI:
![bassmidierror](https://cloud.githubusercontent.com/assets/7596025/8763347/00c11970-2da0-11e5-8ef7-d3a316434ca3.png)

**Comment by Wohlstand** [comment]
Are you ranned install tool as admin? Try also to pause antivirus

**Comment by Alucard648** [comment]
Tried both variants, same error.

**Comment by Wohlstand** [comment]
try to modify access rigts:
Open Folder properties [Панель управления -> параметры папок]
and disable easy shared access [Вкладка 'вид' -> снять галку 'Включить мастер общего доступа']
then open properties of C:\Windows\SysNative\ and in Security [Безопасность] tab add FULL access to users and administrators. Before press [Дополнительно] and set owner [Владелец] to administrators group and close all properties boxes and then open it again.
When you gave rights, try to reinstall BassMidi

**Comment by Alucard648** [comment]
I did`t found SysNative folder, but have a folder, named SysWOW64, where found bassmididrv directory. I am using 64-bit machine.

**Comment by Wohlstand** [comment]
You must see "Изменить" button to enable editing of security options or "Дополнительно" to edit same in advanced way, dig more deep ;-)

**Comment by Alucard648** [comment]
I mean this:
![issue3](https://cloud.githubusercontent.com/assets/7596025/8764660/33d70c52-2df0-11e5-8ed7-7e4d83fda086.png)

**Comment by Wohlstand** [comment]
I warned you than you should seize ownship.
Instead of "Изменить", click "Дополнительно" and then click "Владелец", then select "Администраторы" and apply owner to all contained objects. Because ownship was on "TrustedInstaller", you was hadn't abillity to modify permissions.

**Comment by Alucard648** [comment]
Thanks. Did what you said, but on attempt to reinstall BassMIDI still getting the same error as before.
EDIT: Re-read error message, and tried to assume, that installer tried to write some machine-specific data into bassmididrv.dll after installing it into windows directory. Originally, it should be located in C:/Windows/SysNative/bassmididrv/ , but Windws 7, being 64-bit version, relocated entire driver`s folder into Windows/SysWOW64, and installer couldn`t locate installed directory (and file in question) to perform needed operations and generated this error message. 
Here is the question: does your main PC have 32-bit or 64-bit processor?

**Comment by Wohlstand** [comment]
I have 64-bit processor and 64-bit Windows 7 Ultimate [Максимальная], and same bassmidi installs and works fine anyway

**Comment by Alucard648** [comment]
OK. Installed and configured the driver,  but MIDI`s still don`t play in PGE.

**Comment by Wohlstand** [comment]
Check out volume mixer, because with MS GS was a funny bug: when MIDI file doing fading out, in fact a REAL volume controller going down http://www.supermariobrosx.org/forums/viewtopic.php?p=117906#p117906

**Comment by Alucard648** [comment]
All other MIDI players (XMplay, Windows Media player, Anvil Studio) play MIDIs fine, with all synthesizers(GM, OPL, etc). PGE does not play MIDIs with any synthesizers.

**Comment by Wohlstand** [comment]
than wired. Send me your MIDI file and I will check than on my machine

**Comment by Alucard648** [comment]
Her we go:
http://www.mediafire.com/download/s1sblx3jecpjto3/Circus_Galop_MIDI.mid

**Comment by Wohlstand** [comment]
Oh, I think, I got some SDL2_mixer side error (PGE uses modified version of this library):
```TEXT
get Custom music path
path is D:/_SMBX/SMBX/worlds/Tests/MIDIs/Circus_Galop_MIDI.mid
"Mix_LoadMUS("D:/_SMBX/SMBX/worlds/Tests/MIDIs/Circus_Galop_MIDI.mid"): Unrecognized music format"
"Music type: MUS_NONE"
"Volume changed 128"
"Play nothing: Mix_PlayMusic: Unrecognized music format"
```
I will check out the compilation rules and will fix than bug. I will send a Fixed version of SDL2_mixer.dll file and you will have been able play MIDI's correctly. Than a mistake inside .pro file which defines a compilation rules

**Comment by Wohlstand** [comment]
I tried "Native MIDI" to check out ability to play musics with built-in Windows driver, and has some wired things :-P 
Try to copy SDL2_mixer from old version of PGE (if you have), and put it with newer. Now I'm working with Timidity-based MIDI playback to play MIDI with custom tables (I will make SNES-like patches) and PGE will play MIDI files like SNES

**Comment by Wohlstand** [comment]
Try to download updated version via online installer, and then download one of archives placed here: http://engine.wohlnet.ru/docs/Music/Timididy_banks/ and unpack it into PGE application directory. I just added support of Timidity synthesiser with custom banks.

Than archicves will have: OPL-like bank made by me a long time ago which was my attempt to make chip independent bank, SNES-like which I working currently but wasn't finished it (it have bugs and unfinished!, but you can try it) [Smaller size], and original GUS bank [better quality].

**Comment by Alucard648** [comment]
Thanks. Now it works. OPL and GUS banks are moderately good, but I got used to default "shitty" GM bank.
As for SNES bank development, I would suggest looking into different SNES games for music samples. Super Castlevania 4 has good grand piano and drawbar organ samples, while Link to the Past has some nice string ensemble and harp samples.
Good Luck with this project.
