### ISSUE TITLE
Set Player Start point can flood the History.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#55]
This issue exists since Editor 0.1.0 version.
Clicking and dragging player`s start point floods history with "Set player start point" entries, potentially wiping out important history entries, like errant actions, that should be undone.

**Comment by KevinW1998** [comment]
Mhh, I failed to reproduce the issue:
1.) Do you have the latest version?
2.) Can you provide a direct step-by-step instruction for reproducing the problem?

**Comment by Wohlstand** [comment]
He meant this:
1) click one of "Place player point" buttons
2) hold mousebutton
3) move holden mouse button on area
4) unhold mousebutton
5) hold again and move
6) try to undo. you will get undo by each movement step

**Comment by KevinW1998** [comment]
We should therefore move the place code to mouse release event.

**Comment by Wohlstand** [comment]
No, we should record "place" history event only. This movement is required to calibrate target position in some cases (it more convenient for some people than move mouse without holding of button)

**Comment by KevinW1998** [comment]
But the place code is also in the mousemove event.

**Comment by Wohlstand** [comment]
The player point difference between other elements is:
if point of same ID already placed, it will be moved to target position

**Comment by KevinW1998** [comment]
You can check this on mouse release, no need to check it on mouse move.

**Comment by Wohlstand** [comment]
Fixed https://github.com/Wohlhabend-Networks/PGE-Project/commit/0b2d083d691ad7d286cd4d45ab624ec00f2b4779
