### ISSUE TITLE
PGE fails to load level with unsaved changes.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#56]
Finally decided to give the engine a test run. And found a reproductible issue.
1. Open a level in editor.
2. Make some changes, like moving around a coin or block.
3. Test->Run testing (alpha)
Result: after several seconds of waiting, the level fails to load with "waiting timeout" error message. Saving changes before step 3 results in level loading fine.

**Comment by Wohlstand** [comment]
Try again, its normally now before I will found best interprocessing way than UDP and when I will solve threads-hell

**Comment by Alucard648** [comment]
Thanks. Now for some reason, this worked fine here. No zombies found. Gotta go further testing.
Also encountered a pair of issues that auto-fixed themselves after certain time, such as misplaced warps and player start point.
