### ISSUE TITLE
Victory music does not stop on character`s death after touching exit NPC (kaizo trap).

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#58]
In Super Mario World ROM hacks, if playable character dies after cutting goal tape (thanks to level designer`s cruelity) the victory music is stpped and the death jingle plays. If this occurs in PGE, like falling off bottom of the screen, the victory and death jingles play simultaneously, although level unloads after finishing playing latter.
Test level: https://yadi.sk/d/LiCgBwFXi96Q3

**Comment by Wohlstand** [comment]
therefore I will add aborting of playing of any other sounds before play death jingle (when alone player was alive, is more than 1 players alive, level will still continue)

**Comment by Wohlstand** [comment]
Fixed https://github.com/Wohlhabend-Networks/PGE-Project/commit/c490766e05dad86ac5f3130ad17ea50ea704e513
