### ISSUE TITLE
[Engine] NPC respawns at wrong position after committing suicide

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#60]
1. Let a NPC with hitbox larger than grid size fall down the pit.
2. Scroll his original position off the screen.
3. Return and we have this:
![scr_2015_7_29_18_51_43_522](https://cloud.githubusercontent.com/assets/7596025/8962538/c41005a4-3623-11e5-8aec-6f0505fdd0a8.png)
Test level: https://yadi.sk/d/xuRbAoMTiAFmi

**Comment by Wohlstand** [comment]
This issue caused because I checks collision of NPC's at sides but not at center (where I should align NPC's to nearest side of block [or block group])

**Comment by Alucard648** [comment]
Fix confirmed in latest version.

**Comment by Alucard648** [comment]
Had to reopen issue because it occurs in another test level:
https://yadi.sk/d/mNKPYf1Sj7w7D
Here goombas fall through sizeable solid-on-top platforms after respawning from falling off bottom of the screen.

**Comment by Wohlstand** [comment]
It's common issue in the collizion formula, sorry, I'l fix that

**Comment by Alucard648** [comment]
Yes. I also encountered this issue with rideable NPC`s, like Shy Guys or Mega Moles.

**Comment by Wohlstand** [comment]
I think, I was been fixed that, try the just updated build

**Comment by Wohlstand** [comment]
Glitch no more happens here
