### ISSUE TITLE
[Editor] "Don`t Fill Out of section" state does not carry over between sessions.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#65]
As I said in ticket title, "Don`t Fill Out of section" option state always turns off when closing editor. I did not find flood-filling outside the section boundaries useful, other than testing that 3-second crash protection timer. Having to turn it on on every startup is quite tedious.

**Comment by Wohlstand** [comment]
...because that flag doesn't saving in the configuration

**Comment by Wohlstand** [comment]
That was been resolved some time ago, now "don't fill out of section" is turned on by default.
