### ISSUE TITLE
Typo in message from NPC garbage cleanup tool.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#67]
Screenshot says all.
![gargabe](https://cloud.githubusercontent.com/assets/7596025/9502895/8a3b7780-4c3c-11e5-82fc-0582cf27751d.png)

**Comment by Wohlstand** [comment]
Oops :stuck_out_tongue_winking_eye:

**Comment by cramps-man** [comment]
While on the topic of English and typos, why not we have better English translations for editor and engine? I should be able to do it if you don't mind Wohlstand.

**Comment by KevinW1998** [comment]
Generally I would recommend doing placeholder text, like MSGINFO_GARBAGE_CLEAN and then using with Linguist a english translation. 
In this way:
1.) Changed text doesn't destroy translation
2.) It is way more organized

**Comment by Wohlstand** [comment]
Fixed

**Comment by Alucard648** [comment]
Typo is still persisting in 0.1.3.7
