### ISSUE TITLE
Site got infected.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#78]
Not engine-related issue, but when I tried to enter site with Google Chrome, I got this:
![infected_site](https://cloud.githubusercontent.com/assets/7596025/10483665/3ae3e0fa-7289-11e5-95c8-8cdb1fd63704.png)

**Comment by Wohlstand** [comment]
Oh, shit. I'l check out Yandex Webmaster now where parasit appears

**Comment by Alucard648** [comment]
The warning is still persisting.

**Comment by Wohlstand** [comment]
Need to wait some time when there are will confirm fix

**Comment by Alucard648** [comment]
Error no longer pops out. Closing.
