### ISSUE TITLE
Emulated music does not play

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#79]
Whenever I use emulated music, like VGZ, for custom music it does not play. And if ran testing in the engine, I got this error message:
![emu_music_bug](https://cloud.githubusercontent.com/assets/7596025/10619290/8507c00e-777d-11e5-8f8c-f83bd4d09e71.png)
Test level: https://yadi.sk/d/qsyeqV-ojsuWf
SPC`s work fine, altough this one has quite glitchy playback, despite playing fine in XMPlay
with Alpha SPC player plug-in: https://yadi.sk/d/wAzKyOf2jsuWj

**Comment by Wohlstand** [comment]
VGZ - it's a GZ-ed VGM. Please decompress it and give to that file the VGM extension and retry it.

**Comment by Alucard648** [comment]
Decopressed, works fine, but in properties of library, it`s stated that player can play compressed vgm`s directly as quoted from commit info:
"Now modified SDL Mixer supports new music formats:
...
VGM/VGZ   Sega Master System/Mark III, Sega Genesis/Mega Drive,BBC Micro"

As for NSF`s it would be wise to implement an option to select track to play. Not every game designer would know to append |x at the end of filename path to access tracks from NSF.

**Comment by Wohlstand** [comment]
Don't worry, I will replace that shit with "track №" field which will appear if user selected NSF/HES/etc. multitrack music file. I think you can see in the _Misc folder ther source of dummy SDL Music player which has track № field (I uses it for a music tests only but if you would download Qt 5 and when you will build dependencies, you can open that player in Qt Creator and build it). It will play musics like in PGE or in LunaLUA-SMBX.

**Comment by Alucard648** [comment]
Also I think you should also implement decompressing VGZ`s on the fly or something similar to avoid misleading info about library`s capabilities.

**Comment by Wohlstand** [comment]
Recently I have been fixed this, I have been added ability to decompress GZs from memory, so, PGE (And when I'll send my update to LunaLUA) now finally supports playing of VGZ's.
