### ISSUE TITLE
"Yes", "No" and "Cancel" buttons have wrong language

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#82]
Screenshots say all:
![typo_again](https://cloud.githubusercontent.com/assets/7596025/11237536/a4a19d74-8df1-11e5-97fc-1d907b02db06.png)
![typo_again2](https://cloud.githubusercontent.com/assets/7596025/11237540/a94e2d06-8df1-11e5-8003-dc425486480d.png)

**Comment by Wohlstand** [comment]
Your language is german, try to toggle yout language right in "? -> Language"

**Comment by Alucard648** [comment]
As we can see in screenshots, message boxes have both Gnglish and German language. Language is set to English.

**Comment by Wohlstand** [comment]
I think, that because my deploy script accidentally placed wrong qt_*.qm file and editor took wrong translations of default dialogs. Are you tried to reload editor after this issue? You can remove qt_en.qm file from languages folder and check a result

**Comment by KevinW1998** [comment]
For god sake, no. This is locked to the computer language. Because it is standard dialogs, it will ignore language settings.

**Comment by Alucard648** [comment]
Did some more testing regarding languages and found out, that it was messed even more horribly. French, Italian, Chiniese, Japanese and some other language settings don`t translate anything at all (language remains English), while Russian, German and Portugese translate everything correctly. English still have German for "Yes", "No" and "Cancel" buttons, while Spanish has English for afromentioned buttons.

**Comment by Wohlstand** [comment]
English, Russian, German, Portuguese, Spanish are completed translations, other translations are NOT finished and we are need for help to translate them. Anyway I think to organize simpler way for translators, even I will develop online translation through special web page where everybody authorized can make translation of string data

**Comment by jpmac26** [comment]
I can also confirm that I have this issue as well, and my code is up to date with the latest commit as of 11/23/2015 10:16 AM PST.

**Comment by KevinW1998** [comment]
Wow, that germanzing bug....

**Comment by Wohlstand** [comment]
Okay, I know reason of this bug: because windeployqt.exe appended wrong qt_en.qm, so, it contains German translations of standard sialogs, so, to resolve that just remove it from "languages" folder and everything in English translation will be shown fine. I just updated my deploy scripts to avoid appearence of this junk file.

**Comment by Alucard648** [comment]
Fixed as of latest laboratory build.
