### ISSUE TITLE
After stomping a Koopa, its shell keeps moving

### ISSUE THREAD

**Issue by jpmac26** [Wohlhabend-Networks/PGE-Project#83]
I think the title is fairly self-explanatory, but whenever you stomp a Koopa and it goes into its shell, it does not play the sound effect of stomping, and the shell that appears continues moving at the same speed as the original Koopa, instead of stopping and just sitting on the ground. When we swap enemies like this, we need to reset their movement to follow the movement of the new NPC, not the old one.

**Comment by Wohlstand** [comment]
Solution is adding of onTransform() event function with zeroing of speed. So:
```Lua
function Koopa:onTransform(id)
      self.npc_obj.speedX = 0
end
```
