### ISSUE TITLE
Breeze icons for the UI

### ISSUE THREAD

**Issue by philipzae** [Wohlhabend-Networks/PGE-Project#86]
Would the PGE editor UI like to include a set of monochrome icons that are the default icons used in KDE Plasma 5, as the editor is being built in Qt 5.

**Comment by Wohlstand** [comment]
Yea, I also got idea to make that, but for OS X (where colourful icons are looks not good on the toolbar with everything silver), but for KDE too. PGE is dependent to Qt, and all GUI made on it.

All icon sets are customizable with a theme packs, so, I would add detection of KDE/OS-X and will use monochrome theme as default theme in PGE Editor (anyway there are also config-pack default themes are can be, so, you would to redefine theme in the Tools ->App settings ->view)

**Comment by philipzae** [comment]
Windows 10 has also moved towards flat icons, so using the Breeze icons everywhere would be an advantage, as the interface would look the same everywhere, and for those who dont like the theme, they could easily change it.

I worked with the Breeze team to get it into LibreOffice and Breeze is now default on OS X, KDE and will also be default on Ubuntu in its next release.

So are all the icons used in the UI stored in the /Editor/_resources/images folder of the git repo? Are they all 24x24 in size? Would you prefer them as svgs or pngs, as pngs wont look good on hidpi screens?

**Comment by DarkknightAK** [comment]
If you need some help or are interested in changing your icons I'd like to help. the breeze-icon repository git clone git://anongit.kde.org/breeze-icons
there is also an mirror on github http://github.com/kde/breeze-icons

**Comment by Wohlstand** [comment]
"/Editor/_resources/images" are hardcoded icons which using by editor if no installed themes. Theme-based icons are stored in the repo in "Content/themes/<theme>/..."

**Comment by Wohlstand** [comment]
Added.
Breeze theme will work by default on: KDE, XFCE, OS X and Windows 10

**Comment by philipzae** [comment]
@Wohlstand: I believe @DarkknightAK can design the non-common icons for you if you give him descriptions of how you want it to look - http://help.engine.wohlnet.ru/screenshots/LevelEditing/005_levelEditingSpace.png

**Comment by Wohlstand** [comment]
That screenshot is legacy, and thanks for notification that I should refresh everything, because a lot of updates are been came and a lot of new things are came

**Comment by philipzae** [comment]
Yes the icons in the screenshot are legacy, but the same icons are still being used in the UI and the screenshot does explain what a number of them do.
