### ISSUE TITLE
No config packs were found dialog

### ISSUE THREAD

**Issue by philipzae** [Wohlhabend-Networks/PGE-Project#87]
I noticed two issues when this dialog appears.

1) It says 'Please download and install them into this directory' and the word 'install' didnt make sense to me, so i'd suggest changing it to unzip.

2) After clicking the link and downloading the zip file to the folder and unzipping it, I clicked the 'OK' button in the dialog and the 'Configuration Manager' appeared blank without refreshing the list, which meant i had to click 'Cancel' and open up the editor another time to get the list populated. So i'd suggest that if the no packs dialog appears, clicking 'OK' closing the app.

**Comment by Wohlstand** [comment]
1) Detailed guilde "how to install" http://engine.wohlnet.ru/docs/_configs/how_to_install_config_pack.html
When "PGE Manager" component will be made, it will download/install/update config packs automatically

2) config packs are must be installed into "configs" folder with keeping structure:
```Text
configs/
configs/pack1/main.ini
configs/pack2/main.ini
...
```

I.e. extract contents of downloaded ZIP into "configs" folder directly

**Comment by Wohlstand** [comment]
Anyway, I'll don't spawn that dialog if no configuration packages are installed.
