### ISSUE TITLE
Move game configuration menu items to File menu

### ISSUE THREAD

**Issue by philipzae** [Wohlhabend-Networks/PGE-Project#88]
I was searching for the 'Configuration Manager' dialog entry in the menus and found it quite difficult to find because

1) It isnt found in the File menu
2) Its menu item has a different name

I finally found it under Tools > Global configuration > Change configuration and would like to suggest moving the 3 configuration entries to the bottom of the File menu like so.

- seperator -
Configuration Stats...
Reload Configuration
Configuration Manager...
- seperator -
Exit

**Comment by Wohlstand** [comment]
This menu yesterday has been moved into own menu "Configuration"
