### ISSUE TITLE
Game Engine GLXBadFBConfig Warning Error

### ISSUE THREAD

**Issue by philipzae** [Wohlhabend-Networks/PGE-Project#89]
Tried to run the game engine but got a 'SDL Error: Could not create GL context: GLXBadFBConfig' warning error dialog. Is there a minimum OpenGL version needed to use the game engine as there wasnt any information in the Engine.Readme.txt.

**Comment by Wohlstand** [comment]
Okay, I will add system requirements info. Minimum required OpenGL 3.x. However for video cards which are not supports new OpenGL I plan to implement reserve system (based on the built-in SDL functions) to provide software rendering for case where hardware render is impossible or it is very limited (for example, too small video memory, has no support of the non-pow-of-2 textures, etc.)

**Comment by Wohlstand** [comment]
Done. System requirements are written in the Engine.Readme.txt

**Comment by philipzae** [comment]
Guess i wont be able to test the engine as all i have is opengl 2.1 through my buit in intel driver. :(

**Comment by Wohlstand** [comment]
Anyway, wait my software renderer implementation and you will be able that :wink:
