### ISSUE TITLE
Reorganization of menu bar items

### ISSUE THREAD

**Issue by philipzae** [Wohlhabend-Networks/PGE-Project#90]
I'd like to suggest that you reorder the menu bar items like below for a better user experience and uniformatty with other app menus.

File
Edit
View
Level
World
Test
Script
Tools
Window
Help

**Comment by Wohlstand** [comment]
Please :wink: 
https://github.com/Wohlhabend-Networks/PGE-Project/commit/b6f0695f3c568ed02ba626f1e4fa766b49ae13a7
