### ISSUE TITLE
GIFs2PNG doesn't create transparent images

### ISSUE THREAD

**Issue by jpmac26** [Wohlhabend-Networks/PGE-Project#92]
I have tried tweaking the code in a million ways, but every time I use the program, it creates all the PNGs with solid black backgrounds. I am using the default SMBX 1.3 config pack from the website, and the dev versions of the Editor and Engine both give me "broken image" errors, so I am trying to see if converting them fixes the issue, because when I look at the GIF images in Paint.NET and other programs, they look fine. However, GIFs2PNG cannot fix these images. I have tried so many different things to fix this, and nothing works, please help!

**Comment by Wohlstand** [comment]
You should use argument --config=/PATH/TO/configs/SMBX to make looking for missed masks in the config pack
