### ISSUE TITLE
[Engine] Character can glitch-fall through rideable NPCs

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#96]
Sometimes character can glitch and fall through rideable NPC`s, like platforms, conveyor belts etc.
Test level:https://yadi.sk/d/9_jJqZDOoBLtv
In this level, if character tries to collect coins below "?" blocks, he will glitch through conveyor belt and fall to his doom.

**Comment by Wohlstand** [comment]
Seems this have been fixed and no more happens
