### ISSUE TITLE
Configuration Can't be loaded - Fresh Build Qt 5.5

### ISSUE THREAD

**Issue by KytechN24** [Wohlhabend-Networks/PGE-Project#97]
On a fresh build of PGE on Windows 10 using the sources on GitHub and Qt 5.5 with MinGW 4.9.2 (32 bit), I receive an error after selecting the configuration pack once I start the PGE Editor that States "Configuration can't be loaded. See in [PGE_Editor_log_2016-2-4_18-6-3.txt](https://github.com/Wohlhabend-Networks/PGE-Project/files/118497/PGE_Editor_log_2016-2-4_18-6-3.txt) for more information." I have tried using the config that ships with the sources and also downloading the latest config pack from the website with the same result. Neither of these options have fixed this. The log file mentions an incorrect sRGB profile being reported by libpng in addition to a line stating "Could not parse stylesheet of object 0x3fdeb88".

**Comment by Wohlstand** [comment]
"Config pack can't be loaded" because you wasn't installed full content set into bin-w32/configs/SMBX . Stuff of configuration package in the repo contains ini's and scripts, and no music, sounds and no graphics.

**Comment by KytechN24** [comment]
Installing the full content set and building with Qt. 5.5.1 fixed my issue.
